# Documentation of Sass-lint: https://github.com/sasstools/sass-lint/tree/master/docs
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'src/stylesheets/foundation/_button-group.sass' # have to disable it, cause of 'zero-unit' warning we cannot turn off

rules:
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem

  empty-line-between-blocks:
    - 0
    -
      allow-single-line-rulesets: false

  force-pseudo-nesting:
    - 0

  indentation:
    - 0 # https://github.com/sasstools/sass-lint/issues/393

  leading-zero:
    - 2
    - include: true

  no-color-literals:
    - 2
    -
      allow-rgba: true

  no-duplicate-properties:
    - 2
    -
      exclude: # if you want to provide a fallback for some property, add it here
        - src

  no-misspelled-properties:
    - 0

  quotes:
    - 2
    -
      style: double

  property-sort-order:
    - 2
    - order:
      # Box
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      - display

      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - align-content
      - align-items
      - align-self
      - justify-content
      - order

      - width
      - min-width
      - max-width

      - height
      - min-height
      - max-height

      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left

      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left

      - float
      - clear

      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width

      - transform
      - transform-box
      - transform-origin
      - transform-style

      # Border
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width

      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style

      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius

      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color

      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width

      # Background
      - background
      - background-attachment
      - background-clip
      - background-color
      - background-position # https://github.com/sasstools/sass-lint/issues/494
      - background-image
      - background-size
      - background-repeat

      # Text
      - color

      - font
      - font-family
      - font-size
      - font-smoothing
      - font-style
      - font-variant
      - font-weight

      - letter-spacing
      - line-height
      - list-style

      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-rendering
      - text-shadow
      - text-transform
      - text-wrap

      - white-space
      - word-spacing

      # Transitions
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function

      # Other
      - border-collapse
      - border-spacing
      - box-shadow
      - caption-side
      - content
      - cursor
      - empty-cells
      - overflow
      - quotes
      - speak
      - table-layout
      - vertical-align
      - opacity
      - visibility
