export default {
  content: {
    meta: {
      image: 'https://unsplash.it/810/800?image=10',
    },
    languages: {
      pl: 'Polski',
      en: 'English',
    },
    contact: {
      emailAddress: 'hello@inventi.studio',
      phone1: '+48 514 923 567',
      phone2: '+48 509 723 436',
      place: 'Wrocław, Poland',
    },
    urls: {
      facebook: 'https://www.facebook.com/inventistudio',
      linkedin: 'https://www.linkedin.com/company/inventistudio',
      github: 'https://github.com/InventiStudio',
      repository: 'https://github.com/InventiStudio/portfolio',
      blog: 'https://blog.inventi.studio',
      dribbble: 'https://dribbble.com/inventistudio',
      behance: 'https://www.behance.net/inventistudio',
      instagram: 'https://www.instagram.com/inventistudio',
    },
    technologies: {
      html5:     'HTML 5',
      css3:      'CSS 3',
      js:        'JavaScript (ES6+)',
      vue:       'Vue.js',
      sass:      'Sass',
      webpack:   'Webpack',
      bootstrap: 'Bootstrap',
      babel:     'Babel',
      node:      'Node.js',
      npm:       'npm',
      yarn:      'Yarn',
      karma:     'Karma',
      docker:    'Docker',
      ramda:     'Ramda',
      pug:       'Pug',
      ngnix:     'Nginx',
      eslint:    'ESlint',
      bulma:     'Bulma',
      sequelize: 'Sequelize',
      koa:       'Koa',
      postgres:  'PostgreSQL',
      mongodb:   'MongoDB',
      marvel:    'Marvel App',
      photoshop: 'Photoshop',
      sketch:    'Sketch',
    },
  },
}
